export const quotes = [
    "The best way to predict the future is to invent it. - Alan Kay",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. - Buddha",
    "Act as if what you do makes a difference. It does. - William James",
    "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "Your time is limited, don’t waste it living someone else’s life. - Steve Jobs",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Dream big and dare to fail. - Norman Vaughan",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "Don’t count the days, make the days count. - Muhammad Ali",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    "Keep going. Be all in. - Bryan Hutchinson",
    "Happiness is not by chance, but by choice. - Jim Rohn",
    "Stay hungry, stay foolish. - Steve Jobs",
    "Life is short, and it is up to you to make it sweet. - Sarah Louise Delany",
    "Do what you feel in your heart to be right – for you’ll be criticized anyway. - Eleanor Roosevelt",
    "Be the change that you wish to see in the world. - Mahatma Gandhi",
    "Turn your wounds into wisdom. - Oprah Winfrey",
    "When you have a dream, you’ve got to grab it and never let go. - Carol Burnett",
    "Nothing is impossible. The word itself says ‘I’m possible!’ - Audrey Hepburn",
    "Whether you think you can or you think you can’t, you’re right. - Henry Ford",
    "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein",
    "Everything has beauty, but not everyone can see. - Confucius",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "The secret of getting ahead is getting started. - Mark Twain",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "Opportunities don't happen, you create them. - Chris Grosser",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "I never dreamed about success, I worked for it. - Estee Lauder",
    "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
    "Don’t watch the clock; do what it does. Keep going. - Sam Levenson",
    "The harder you work for something, the greater you’ll feel when you achieve it. - Anonymous",
    "Believe in yourself and all that you are. - Christian D. Larson",
    "Doubt kills more dreams than failure ever will. - Suzy Kassem",
    "In the middle of every difficulty lies opportunity. - Albert Einstein",
    "Do one thing every day that scares you. - Eleanor Roosevelt",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "Hustle in silence and let your success make the noise. - Anonymous",
    "Don’t limit your challenges. Challenge your limits. - Anonymous",
    "It always seems impossible until it’s done. - Nelson Mandela",
    "Your limitation—it’s only your imagination. - Anonymous",
    "Dream it. Wish it. Do it. - Anonymous",
    "Sometimes later becomes never. Do it now. - Anonymous",
    "The harder you work, the luckier you get. - Gary Player",
    "You can waste your lives drawing lines. Or you can live your life crossing them. - Shonda Rhimes",
    "Failure is the condiment that gives success its flavor. - Truman Capote",
    "It’s never too late to be what you might have been. - George Eliot",
    "Fall seven times and stand up eight. - Japanese Proverb",
    "If you can dream it, you can do it. - Walt Disney",
    "Shoot for the moon. Even if you miss, you’ll land among the stars. - Norman Vincent Peale",
    "If you want to achieve greatness stop asking for permission. - Anonymous",
    "Don’t stop when you’re tired. Stop when you’re done. - Anonymous",
    "You can do anything, but not everything. - David Allen",
    "Success is a journey, not a destination. - Ben Sweetland",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "You get in life what you have the courage to ask for. - Oprah Winfrey",
    "If you want something new, you have to stop doing something old. - Peter Drucker",
    "Failure will never overtake me if my determination to succeed is strong enough. - Og Mandino",
    "Don’t let yesterday take up too much of today. - Will Rogers",
    "Do not wait to strike till the iron is hot; but make it hot by striking. - William Butler Yeats",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Knowing is not enough; we must apply. Willing is not enough; we must do. - Johann Wolfgang von Goethe",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Opportunities are usually disguised as hard work, so most people don’t recognize them. - Ann Landers",
    "If you can’t explain it simply, you don’t understand it well enough. - Albert Einstein",
    "Try not to become a man of success, but rather try to become a man of value. - Albert Einstein",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "The mind is everything. What you think you become. - Buddha",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "What we achieve inwardly will change outer reality. - Plutarch",
    "Perseverance is failing 19 times and succeeding the 20th. - Julie Andrews",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "You don’t have to control your thoughts. You just have to stop letting them control you. - Dan Millman",
    "The best revenge is massive success. - Frank Sinatra"
];
